<?php
ini_set('display_errors', 1);
error_reporting(E_ALL);
ob_start();
session_start();
$data = date('%d de %B de %Y');
date_default_timezone_set('Africa/Luanda');
setlocale(LC_TIME, 'pt_br.utf-8');
include($_SERVER['DOCUMENT_ROOT'] . "/siga/session/conexao.php");
//include($_SERVER['DOCUMENT_ROOT'] . '/siga/controllers/relAlunoTurma.php');
require_once $_SERVER['DOCUMENT_ROOT'] . "/siga/fpdf/fpdf.php";

$nome = $_SESSION["nome"];

//include($_SERVER['DOCUMENT_ROOT'] . "/siga/controllers/controllerRelAlunoTurma.php");
Class PDF extends FPDF {
    function Header() {
        $this->SetFont('Arial', 'B', 12);
        $this->Image($_SERVER['DOCUMENT_ROOT'] . '/siga/views/assets/build/images/insignia.png', 95, 16, 16);
        $this->Ln(26);
        $this->Cell(0, 5, 'REPÚBLICA DE ANGOLA', 0, 0, 'C');
        $this->Ln(5);
        $this->Cell(0, 5, 'ADMINISTRAÇÃO MUNICIPAL DE BENGUELA', 0, 0, 'C');
        $this->Ln(5);
        $this->Cell(0, 5, 'DIREÇÃO MUNICIPAL DA EDUCAÇÃO DE BENGUELA', 0, 0, 'C');
        $this->Ln(5);
        $this->Cell(0, 5, 'COMPLEXO ESCOLAR BG Nº 1237', 0, 0, 'C');
        $this->Ln(10);
    }

    public function Footer() {
      global $nome;
        $this->SetY(-15);
        $this->SetX(25);
        $this->SetFont('Arial', 'I', 8);
        $this->Cell(72, 10, 'Fonte: SIGA - Sistema Integrado de Gestão Academica', 0, 0, 'L');
        $this->Cell(30, 10, 'Data: ' . date('d / m / Y'), 0, 0, 'C');
        $this->Cell(63, 10, 'Utilizador: ' . $nome , 0, 0, 'R');
    }
}

$getId= filter_input(INPUT_GET, 'id', FILTER_SANITIZE_NUMBER_INT);

$Idmatricula ='';
$Numatricula ='';
$Nomealuno =''; 
$Datanasc =''; 
$Genero =''; 
$Municipio ='';   
$Provincia =''; 
$Documento =''; 
$Numero ='';
$Dataemissao='';
$Pai =''; 
$Mae =''; 
$Cidade ='';
$Bairro ='';
$Rua ='';
$Telf =''; 
$Obs ='';
$Classe ='';
$Turma ='';
$Periodo ='';
$Sala =''; 
$Anoletivo ='';
$Lingua ='';
$Datamatricula ='';
$Encarregado ='';
$Telfenc ='';
$Tipomatricula ='';
  $sqlAlunos = "SELECT  *FROM vwmatriculas WHERE idmatricula=:idmatricula LIMIT 1";
  $pst = $conectar->prepare($sqlAlunos);
  $pst->bindParam(":idmatricula", $getId);
  $pst->execute();
  $resultado = $pst->fetchAll();

$pdf = new PDF();
$pdf->AddPage('P', 'A4');
$pdf->AliasNbPages();
$pdf->Cell(0, 5, 'FICHA DE MATRÍCULA', 0, 0, 'C');
$pdf->Ln(5);
foreach ($resultado as $dados) {
 extract($dados);
$Idmatricula =$idmatricula;
$Numatricula =$numatricula;
$Nomealuno =$nomealuno;
$Datanasc =$datanasc;
$Genero =$genero;
$Municipio =$municipio ;
$Provincia =$provincia; 
$Documento =$documento; 
$Numero =$numero; 
$Dataemissao=$dataemissao;
$Pai =$pai; 
$Mae =$mae; 
$Cidade =$cidade;
$Bairro =$bairro;
$Rua =$rua;
$Telf =$telf; 
$Obs =$obs;
$Classe =$classe;
$Turma =$turma;
$Periodo =$periodo;
$Sala =$sala; 
$Anoletivo =$anoletivo;
$Lingua =$lingua;
$Datamatricula =$datamatricula;
$Encarregado =$encarregado;
$Telfenc =$telfenc;
$Tipomatricula =$tipomatricula;
 
  } 
$pdf->Ln(10);
$pdf->SetFont('Arial', 'B');
$pdf->Cell(51, 12, 'Tipo de aluno:', 0, 0, 'R', 0);
$pdf->SetFont('Arial');
$pdf->Cell(1, 12, $Tipomatricula, 0, 0, 'L', 0);
$pdf->SetFont('Arial', 'B');
$pdf->Cell(102, 12, 'Nº de Matrícula:', 0, 0, 'R', 0);
$pdf->SetFont('Arial');
$pdf->Cell(1, 12, $Numatricula, 0, 0, 'L', 0);
$pdf->Ln(10);
$pdf->setX(25);
$pdf->SetFont('Arial', 'B');
$pdf->SetFillColor(177, 177, 177);
$pdf->SetTextColor(255, 255, 255);
$pdf->Cell(165, 8, 'DADOS PESSOAIS ', 1, 0, 'C', 1);
$pdf->Ln(8);
$pdf->SetFontSize(10);
$pdf->SetFont('Arial', 'B');
$pdf->setX(25);
$pdf->SetFillColor(177, 177, 177);
$pdf->SetTextColor(0, 0, 0);
$pdf->Cell(34, 10, 'NOME COMPLETO', 1, 0, 'L', 0);
$pdf->SetFont('Arial');
$pdf->Cell(65, 10, $Nomealuno, 1, 0, 'L', 0);
$pdf->SetFont('Arial', 'B');
$pdf->Cell(46, 10, 'DATA DE NASCIMENTO:', 1, 0, 'R', 0);
$pdf->SetFont('Arial');
$pdf->Cell(20, 10, $Datanasc, 1, 0, 'L', 0);
$pdf->Ln(10);
$pdf->setX(25);
$pdf->SetFont('Arial', 'B');
$pdf->Cell(25, 10, 'TIPO DE DOC.', 1, 0, 'L', 0);
$pdf->SetFont('Arial');
$pdf->Cell(9, 10, $Documento, 1, 0, 'C', 0);
$pdf->SetFont('Arial', 'B');
$pdf->Cell(31, 10, 'Nº DO DOC:', 1, 0, 'R', 0);
$pdf->SetFont('Arial');
$pdf->Cell(34, 10, $Numero, 1, 0, 'C', 0);
$pdf->SetFont('Arial', 'B');
$pdf->Cell(46, 10, 'DATA DE EMISSÃO', 1, 0, 'R', 0);
$pdf->SetFont('Arial');
$pdf->Cell(20, 10, $Dataemissao, 1, 0, 'L', 0);
$pdf->Ln(10);
$pdf->setX(25);
$pdf->SetFont('Arial', 'B');
$pdf->Cell(34, 10, 'LOCAL DE NASC.', 1, 0, 'L', 0);
$pdf->SetFont('Arial');
$pdf->Cell(31, 10, $Municipio, 1, 0, 'L', 0);
$pdf->SetFont('Arial', 'B');
$pdf->Cell(22, 10, 'MUNICÍPIO', 1, 0, 'R', 0);
$pdf->SetFont('Arial');
$pdf->Cell(31, 10, $Municipio, 1, 0, 'L', 0);
$pdf->SetFont('Arial', 'B');
$pdf->Cell(22, 10, 'PROVÍNCIA', 1, 0, 'R', 0);
$pdf->SetFont('Arial');
$pdf->Cell(25, 10, $Provincia, 1, 0, 'L', 0);
$pdf->Ln(10);
$pdf->setX(25);
$pdf->SetFont('Arial', 'B');
$pdf->Cell(34, 10, 'NOME DO PAI', 1, 0, 'L', 0);
$pdf->SetFont('Arial');
$pdf->Cell(53, 10, $Pai, 1, 0, 'L', 0);
$pdf->SetFont('Arial', 'B');
$pdf->Cell(31, 10, 'NOME DA MÃE', 1, 0, 'R', 0);
$pdf->SetFont('Arial');
$pdf->Cell(47, 10, $Mae, 1, 0, 'L', 0);
$pdf->Ln(10);
$pdf->setX(25);
$pdf->SetFont('Arial', 'B');
$pdf->SetFillColor(177, 177, 177);
$pdf->SetTextColor(255, 255, 255);
$pdf->Cell(165, 8, 'MORADA E CONTACTOS', 1, 0, 'C', 1);
$pdf->Ln(8);
$pdf->setX(25);
$pdf->SetFont('Arial', 'B');
$pdf->SetTextColor(0, 0, 0);
$pdf->Cell(25, 10, 'CIDADE', 1, 0, 'L', 0);
$pdf->SetFont('Arial');
$pdf->Cell(24, 10, $Cidade, 1, 0, 'L', 0);
$pdf->SetFont('Arial', 'B');
$pdf->Cell(16, 10, 'BAIRRO', 1, 0, 'R', 0);
$pdf->SetFont('Arial');
$pdf->Cell(53, 10, $Bairro, 1, 0, 'L', 0);
$pdf->SetFont('Arial', 'B');
$pdf->Cell(22, 10, 'RUA', 1, 0, 'R', 0);
$pdf->SetFont('Arial');
$pdf->Cell(25, 10, $Rua, 1, 0, 'L', 0);
$pdf->Ln(10);
$pdf->setX(25);
$pdf->SetFont('Arial', 'B');
$pdf->Cell(25, 10, 'TELEFONE', 1, 0, 'L', 0);
$pdf->SetFont('Arial');
$pdf->Cell(40, 10, $Telf, 1, 0, 'L', 0);
$pdf->SetFont('Arial', 'B');
$pdf->Cell(34, 10, 'ENC. DE EDUCA.', 1, 0, 'R', 0);
$pdf->SetFont('Arial');
$pdf->Cell(66, 10, $Encarregado, 1, 0, 'L', 0);
$pdf->Ln(10);
$pdf->SetX(25);
$pdf->SetFont('Arial', 'B');
$pdf->Cell(34, 10, 'LOCAL DE TRAB.', 1, 0, 'L', 0);
$pdf->SetFont('Arial');
$pdf->Cell(53, 10, '', 1, 0, 'L', 0);
$pdf->SetFont('Arial', 'B');
$pdf->Cell(31, 10, 'TELEFONE', 1, 0, 'L', 0);
$pdf->SetFont('Arial');
$pdf->Cell(47, 10, $Telfenc, 1, 0, 'L', 0);
$pdf->Ln(10);
$pdf->setX(25);
$pdf->SetFont('Arial', 'B');
$pdf->SetFillColor(177, 177, 177);
$pdf->SetTextColor(255, 255, 255);
$pdf->Cell(165, 8, 'DADOS ESCOLARES', 1, 0, 'C', 1);
$pdf->Ln(8);
$pdf->setX(25);
$pdf->SetFont('Arial', 'B');
$pdf->SetTextColor(0, 0, 0);
$pdf->Cell(25, 10, 'CLASSE', 1, 0, 'L', 0);
$pdf->SetFont('Arial');
$pdf->Cell(9, 10, $Classe, 1, 0, 'L', 0);
$pdf->SetFont('Arial', 'B');
$pdf->Cell(15, 10, 'TURMA', 1, 0, 'R', 0);
$pdf->SetFont('Arial');
$pdf->Cell(16, 10, $Turma, 1, 0, 'L', 0);
$pdf->SetFont('Arial', 'B');
$pdf->Cell(22, 10, 'PERÍODO', 1, 0, 'R', 0);
$pdf->SetFont('Arial');
$pdf->Cell(31, 10, $Periodo, 1, 0, 'L', 0);
$pdf->SetFont('Arial', 'B');
$pdf->Cell(27, 10, 'ANO LECTIVO', 1, 0, 'R', 0);
$pdf->SetFont('Arial');
$pdf->Cell(20, 10, $Anoletivo, 1, 0, 'L', 0);
$pdf->Ln(10);
$pdf->setX(25);
$pdf->SetFont('Arial', 'B');
$pdf->SetTextColor(0, 0, 0);
$pdf->Cell(34, 10, 'L. ESTRANGEIRA', 1, 0, 'L', 0);
$pdf->SetFont('Arial');
$pdf->Cell(15, 10, $Lingua, 1, 0, 'L', 0);
$pdf->SetFont('Arial', 'B');
$pdf->Cell(16, 10, 'OBS', 1, 0, 'R', 0);
$pdf->SetFont('Arial');
$pdf->Cell(100, 10, $Obs, 1, 0, 'L', 0);
$pdf->Ln(10);
$pdf->setX(25);
$pdf->SetFont('Arial', 'B');
$pdf->Cell(165, 10, 'DATA DA MATRÍCULA : ' . $Datamatricula, 1, 0, 'L', 0);
$pdf->Ln(15);
global $conectar;
          $sql="SELECT * FROM tbconfig ORDER BY idinicio ASC";
          $stmt=$conectar->prepare($sql);
          $stmt->execute();
          $res=$stmt->fetchAll();
          foreach ($res as $key) {
          extract($key);
          $diretor=$nomediretor;
          $pedago=$nomepedagogico;
        }
$pdf->SetTextColor(0, 0, 0);
$pdf->setX(25);
$pdf->SetFont('Arial', 'B');
$pdf->Cell(55, 12, 'O Director', 0, 0, 'C');
$pdf->Cell(55, 12, 'O Aluno ou Encarregado', 0, 0, 'C');
$pdf->Cell(55, 12, 'O Pedagógico', 0, 0, 'C');
$pdf->Ln(10);
$pdf->setX(25);
$pdf->Cell(55, 12, $diretor, 0, 0, 'C');
$pdf->Cell(55, 5, '_________________________', 0, 0, 'C');
$pdf->Cell(55, 12, $pedago, 0, 0, 'C');
$pdf->Ln(8);
$pdf->SetX(25);
$pdf->SetFont('Arial', 'I', 8);
$pdf->Cell(72, 10, 'Fonte: SIGA - Sistema Integrado de Gestão Academica', 0, 0, 'L');
$pdf->Cell(30, 10, 'Data: ' . date('d / m / Y'), 0, 0, 'C');
$pdf->Cell(63, 10, 'Utilizador: ' . $nome, 0, 0, 'R');
$pdf->Ln(10);
$y = 243;
// Desenha a linha
$pdf->SetLineWidth(0.5);
$pdf->Line(10, $y, 200, $y);
$pdf->setX(25);
$pdf->SetFont('Arial', 'B');
$pdf->SetFillColor(177, 177, 177);
$pdf->SetTextColor(255, 255, 255);
$pdf->Cell(165, 8, 'RECIBO', 1, 0, 'C', 1);
$pdf->Ln(8);
$pdf->SetFont('Arial', 'B');
$pdf->setX(25);
$pdf->SetFillColor(177, 177, 177);
$pdf->SetTextColor(0, 0, 0);
$pdf->Cell(34, 6, 'NOME COMPLETO', 1, 0, 'L', 0);
$pdf->SetFont('Arial');
$pdf->Cell(65, 6, $Nomealuno, 1, 0, 'L', 0);
$pdf->SetFont('Arial', 'B');
$pdf->Cell(36, 6, 'Nº de Matrícula:', 1, 0, 'R', 0);
$pdf->SetFont('Arial');
$pdf->Cell(30, 6, $Numatricula, 1, 0, 'L', 0);
$pdf->Ln(6);
$pdf->setX(25);
$pdf->SetFont('Arial', 'B');
$pdf->Cell(25, 6, 'CLASSE', 1, 0, 'L', 0);
$pdf->SetFont('Arial');
$pdf->Cell(9, 6, $Classe, 1, 0, 'L', 0);
$pdf->SetFont('Arial', 'B');
$pdf->Cell(25, 6, 'TURMA', 1, 0, 'R', 0);
$pdf->SetFont('Arial');
$pdf->Cell(9, 6, $Turma, 1, 0, 'L', 0);
$pdf->SetFont('Arial', 'B');
$pdf->Cell(31, 6, 'PERÍODO', 1, 0, 'R', 0);
$pdf->SetFont('Arial');
$pdf->Cell(20, 6, $Periodo, 1, 0, 'L', 0);
$pdf->SetFont('Arial', 'B');
$pdf->Cell(30, 6, 'ANO LECTIVO', 1, 0, 'R', 0);
$pdf->SetFont('Arial');
$pdf->Cell(16, 6, $Anoletivo, 1, 0, 'L', 0);
$pdf->Ln(6);
$pdf->setX(25);
$pdf->SetFont('Arial', 'B');
$pdf->Cell(34, 6, 'DATA DA MATRIC.', 1, 0, 'L', 0);
$pdf->SetFont('Arial');
$pdf->Cell(34, 6, $Datamatricula, 1, 0, 'L', 0);
$pdf->SetFont('Arial', 'B');
$pdf->Cell(31, 6, 'ASS.FUNCIONÁRIO', 1, 0, 'R', 0);
$pdf->SetFont('Arial');
$pdf->Cell(66, 6, '', 1, 0, 'L', 0);
$pdf->Ln(6);
$pdf->setX(25);
$pdf->SetFont('Arial', 'IB');
$pdf->SetFontSize(6);
$pdf->Cell(165, 6, 'CONSERVAR ESTE RECIBO ATÉ O INICIO DAS AULAS', 0, 0, 'L', 0);

/*
  foreach ($resultado as $row) {
  extract($row);
  $pdf->Ln();
  $pdf->setX(30);
  $pdf->SetTextColor(0, 0, 0);
  $pdf->Cell(20, 12, $idmatricula, 1, 0, 'C');
  $pdf->Cell(60, 12, $nomealuno, 1, 0, 'L');
  $pdf->Cell(20, 12, $genero, 1, 0, 'C');
  $pdf->Cell(40, 12, $tipomatricula, 1, 0, 'C');
  }
 */

$pdf->Output('FichaAluno.pdf', 'I');
ob_end_flush();

